<?php
$i=$OBJECT_FIELD_SCALE_X;		$data[$i]->name="OBJECT_FIELD_SCALE_X";					$data[$i]->dbfield="size";				$data[$i]->type="FLOAT";
//this is used at beast lore
$i=$UNIT_FIELD_MAXHEALTH;		$data[$i]->name="UNIT_FIELD_MAXHEALTH";					$data[$i]->dbfield="maxhealth";			$data[$i]->donotuseif=100;
//this is used for "enslave demon"
$i=$UNIT_FIELD_BASE_HEALTH;		$data[$i]->name="UNIT_FIELD_BASE_HEALTH";				$data[$i]->dbfield="maxhealth";			$data[$i]->donotuseif=100;
$i=$UNIT_FIELD_POWER1;			$data[$i]->name="UNIT_FIELD_MAXPOWER1";					$data[$i]->dbfield="pow1";
$i=$UNIT_FIELD_POWER2;			$data[$i]->name="UNIT_FIELD_MAXPOWER2";					$data[$i]->dbfield="pow2";
$i=$UNIT_FIELD_POWER3;			$data[$i]->name="UNIT_FIELD_MAXPOWER3";					$data[$i]->dbfield="pow3";
$i=$UNIT_FIELD_POWER4;			$data[$i]->name="UNIT_FIELD_MAXPOWER4";					$data[$i]->dbfield="pow4";
$i=$UNIT_FIELD_POWER5;			$data[$i]->name="UNIT_FIELD_MAXPOWER5";					$data[$i]->dbfield="pow5";
$i=$UNIT_FIELD_LEVEL;			$data[$i]->name="UNIT_FIELD_LEVEL";						$data[$i]->dbfield="level_max";
$i=$UNIT_FIELD_FACTIONTEMPLATE;	$data[$i]->name="UNIT_FIELD_FACTIONTEMPLATE";			$data[$i]->dbfield="faction";
$i=$UNIT_FIELD_BYTES_0;			$data[$i]->name="UNIT_FIELD_BYTES_0";					$data[$i]->dbfield="bytes_0";
$i=$UNIT_VIRTUAL_ITEM_SLOT_DISPLAY;		$data[$i]->name="UNIT_VIRTUAL_ITEM_SLOT_DISPLAY1";		$data[$i]->dbfield="item_model_1";
$i=$UNIT_VIRTUAL_ITEM_SLOT_DISPLAY_01;	$data[$i]->name="UNIT_VIRTUAL_ITEM_SLOT_DISPLAY2";		$data[$i]->dbfield="item_model_2";
$i=$UNIT_VIRTUAL_ITEM_SLOT_DISPLAY_02;	$data[$i]->name="UNIT_VIRTUAL_ITEM_SLOT_DISPLAY3";		$data[$i]->dbfield="item_model_3";
$i=$UNIT_VIRTUAL_ITEM_INFO;		$data[$i]->name="UNIT_VIRTUAL_ITEM_INFO1";				$data[$i]->dbfield="item_info_1";
$i=$UNIT_VIRTUAL_ITEM_INFO_01;	$data[$i]->name="UNIT_VIRTUAL_ITEM_INFO2";				$data[$i]->dbfield="item_info_2";
$i=$UNIT_VIRTUAL_ITEM_INFO_02;	$data[$i]->name="UNIT_VIRTUAL_ITEM_INFO3";				$data[$i]->dbfield="item_info_3";
$i=$UNIT_VIRTUAL_ITEM_INFO_03;	$data[$i]->name="UNIT_VIRTUAL_ITEM_INFO4";				$data[$i]->dbfield="item_info_4";
$i=$UNIT_VIRTUAL_ITEM_INFO_04;	$data[$i]->name="UNIT_VIRTUAL_ITEM_INFO5";				$data[$i]->dbfield="item_info_5";
$i=$UNIT_VIRTUAL_ITEM_INFO_05;	$data[$i]->name="UNIT_VIRTUAL_ITEM_INFO6";				$data[$i]->dbfield="item_info_6";
$i=$UNIT_FIELD_FLAGS;			$data[$i]->name="UNIT_FIELD_FLAGS";						$data[$i]->dbfield="flags1";			$data[$i]->type="FLAGS";
$i=$UNIT_FIELD_AURA;			$data[$i]->name="UNIT_FIELD_AURA";						$data[$i]->dbfield="aura_0";
$i=$UNIT_FIELD_AURA_01;			$data[$i]->name="UNIT_FIELD_AURA";						$data[$i]->dbfield="aura_1";
$i=$UNIT_FIELD_AURA_02;			$data[$i]->name="UNIT_FIELD_AURA";						$data[$i]->dbfield="aura_2";
$i=$UNIT_FIELD_AURA_32;			$data[$i]->name="UNIT_FIELD_AURA";						$data[$i]->dbfield="aura_32";
$i=$UNIT_FIELD_AURAFLAGS;		$data[$i]->name="UNIT_FIELD_AURAFLAGS";					$data[$i]->dbfield="aura_flags_0";
$i=$UNIT_FIELD_AURALEVELS;		$data[$i]->name="UNIT_FIELD_AURALEVELS";				$data[$i]->dbfield="aura_levels_0";
$i=$UNIT_FIELD_AURAAPPLICATIONS;$data[$i]->name="UNIT_FIELD_AURAAPPLICATIONS";			$data[$i]->dbfield="aura_applications_0";
$i=$UNIT_FIELD_AURASTATE;		$data[$i]->name="UNIT_FIELD_AURASTATE";					$data[$i]->dbfield="aurastate";
$i=$UNIT_FIELD_BASEATTACKTIME;	$data[$i]->name="UNIT_FIELD_BASEATTACKTIME";			$data[$i]->dbfield="attack_melee";
$i=$UNIT_FIELD_BASEATTACKTIME_01;	$data[$i]->name="UNIT_FIELD_BASEATTACKTIME1";		$data[$i]->dbfield="attack_melee2";
$i=$UNIT_FIELD_RANGEDATTACKTIME;	$data[$i]->name="UNIT_FIELD_RANGEDATTACKTIME";		$data[$i]->dbfield="atack_ranged";
$i=$UNIT_FIELD_BOUNDINGRADIUS;	$data[$i]->name="UNIT_FIELD_BOUNDINGRADIUS";			$data[$i]->dbfield="bounding_radius";	$data[$i]->type="FLOAT";
$i=$UNIT_FIELD_COMBATREACH;		$data[$i]->name="UNIT_FIELD_COMBATREACH";				$data[$i]->dbfield="combat_reach";		$data[$i]->type="FLOAT";
$i=$UNIT_FIELD_DISPLAYID;		$data[$i]->name="UNIT_FIELD_DISPLAYID";					$data[$i]->dbfield="model";
$i=$UNIT_FIELD_NATIVEDISPLAYID;		$data[$i]->name="UNIT_FIELD_NATIVEDISPLAYID";		$data[$i]->dbfield="model_orig";
$i=$UNIT_FIELD_MOUNTDISPLAYID;	$data[$i]->name="UNIT_FIELD_MOUNTDISPLAYID";			$data[$i]->dbfield="mount";
$i=$UNIT_FIELD_MINDAMAGE;		$data[$i]->name="UNIT_FIELD_MINDAMAGE";					$data[$i]->dbfield="damage_min";		$data[$i]->type="FLOAT";		$data[$i]->updtype="MIN";
$i=$UNIT_FIELD_MAXDAMAGE;		$data[$i]->name="UNIT_FIELD_MAXDAMAGE";					$data[$i]->dbfield="damage_max";		$data[$i]->type="FLOAT";
$i=$UNIT_FIELD_MINOFFHANDDAMAGE;	$data[$i]->name="UNIT_FIELD_MINOFFHANDDAMAGE";		$data[$i]->dbfield="min_offhand_dmg";	$data[$i]->type="FLOAT";		$data[$i]->updtype="MIN";
$i=$UNIT_FIELD_MAXOFFHANDDAMAGE;	$data[$i]->name="UNIT_FIELD_MAXOFFHANDDAMAGE";		$data[$i]->dbfield="max_offhand_dmg";	$data[$i]->type="FLOAT";
$i=$UNIT_FIELD_BYTES_1;			$data[$i]->name="UNIT_FIELD_BYTES_1";					$data[$i]->dbfield="bytes_1";
$i=$UNIT_NPC_FLAGS;				$data[$i]->name="UNIT_NPC_FLAGS";						$data[$i]->dbfield="npcflags";			$data[$i]->type="FLAGS";
$i=$UNIT_FIELD_STAT0;			$data[$i]->name="UNIT_FIELD_STRENGTH";					$data[$i]->dbfield="strength";
$i=$UNIT_FIELD_STAT1;			$data[$i]->name="UNIT_FIELD_AGILITY";					$data[$i]->dbfield="agility";
$i=$UNIT_FIELD_STAT2;			$data[$i]->name="UNIT_FIELD_STAMINA";					$data[$i]->dbfield="stamina";
$i=$UNIT_FIELD_STAT3;			$data[$i]->name="UNIT_FIELD_INTELLECT";					$data[$i]->dbfield="intelect";
$i=$UNIT_FIELD_STAT4;			$data[$i]->name="UNIT_FIELD_SPIRIRT";					$data[$i]->dbfield="spirit";
$i=$UNIT_FIELD_RESISTANCES;		$data[$i]->name="UNIT_FIELD_RESISTANCES1";				$data[$i]->dbfield="rezist_0";
$i=$UNIT_FIELD_RESISTANCES_01;	$data[$i]->name="UNIT_FIELD_RESISTANCES2";				$data[$i]->dbfield="rezist_1";
$i=$UNIT_FIELD_RESISTANCES_02;	$data[$i]->name="UNIT_FIELD_RESISTANCES3";				$data[$i]->dbfield="rezist_2";
$i=$UNIT_FIELD_RESISTANCES_03;	$data[$i]->name="UNIT_FIELD_RESISTANCES4";				$data[$i]->dbfield="rezist_3";
$i=$UNIT_FIELD_RESISTANCES_04;	$data[$i]->name="UNIT_FIELD_RESISTANCES5";				$data[$i]->dbfield="rezist_4";
$i=$UNIT_FIELD_RESISTANCES_05;	$data[$i]->name="UNIT_FIELD_RESISTANCES6";				$data[$i]->dbfield="rezist_5";
$i=$UNIT_FIELD_RESISTANCES_06;	$data[$i]->name="UNIT_FIELD_RESISTANCES7";				$data[$i]->dbfield="rezist_6";
$i=0;		//$data[181]->name="UNIT_FIELD_BASE_MANA";			$data[181]->dbfield="";
$i=$UNIT_FIELD_BYTES_2;			$data[$i]->name="UNIT_FIELD_BYTES_2";					$data[$i]->dbfield="bytes_2";
$i=$UNIT_FIELD_ATTACK_POWER;	$data[$i]->name="UNIT_FIELD_ATTACK_POWER";				$data[$i]->dbfield="attack_power";
$i=$UNIT_FIELD_RANGED_ATTACK_POWER;	$data[$i]->name="UNIT_FIELD_RANGED_ATTACK_POWER";	$data[$i]->dbfield="ranged_attack_power";
$i=$UNIT_FIELD_MINRANGEDDAMAGE;	$data[$i]->name="UNIT_FIELD_MINRANGEDDAMAGE";			$data[$i]->dbfield="ranged_dmg_min";	$data[$i]->type="FLOAT";		$data[$i]->updtype="MIN";
$i=$UNIT_FIELD_MAXRANGEDDAMAGE;	$data[$i]->name="UNIT_FIELD_MAXRANGEDDAMAGE";			$data[$i]->dbfield="ranged_dmg_max";	$data[$i]->type="FLOAT";
$UNIT_END	=  0xE8;
?>