// This file was automatically generated by the SVN revision extractor.
// There is no need to modify it.

#ifndef SVN_REVISION_H
#define SVN_REVISION_H

static const char * BUILD_TAG = "TRUNK";
static int BUILD_REVISION = 0;

#define EXTRACT_REVISION_NUMBER() { char ttext[50]; sscanf( AUTO_REVISION,"%s %d",ttext,&BUILD_REVISION); }

#define AUTO_REVISION "$Revision: 2779 $"

#endif		 // SVN_REVISION_H

